apiVersion: mutations.gatekeeper.sh/v1beta1
kind: Assign
metadata:
  name: append-valid-suffix-to-image
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["*"]
      kinds: ["Pod"]
  location: "spec.containers[name: *].image"
  parameters:
    assign:
      externalData:
        provider: external-data-provider
        dataSource: ValueAtLocation
