apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sExternalDataValidation
metadata:
  name: deny-images-with-invalid-suffix
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["*"]
        kinds: ["Pod"]
